version: "3.7"

x-app-common:
  &app-common
  build:
    context: .
    dockerfile: Dockerfile
  env_file:
    - .envs/app.env
  volumes:
    - ./src:/app
  networks:
    - face_recognition_network

services:
  sidecar:
    <<: *app-common
    volumes:
      - ./src:/app
      # Extend homes to preserve bash and python history (DX)
      - app-roothome:/root
    ports:
      - "1722:1722"

  postgres:
    image: postgres:13.2
    ports:
      - "5432:5432"
    env_file:
      - ./.envs/.postgres
      - ./.envs/app.env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - face_recognition_network



networks:
  face_recognition_network:
    driver: bridge

volumes:
  postgres:
  app-apphome:
  app-roothome:
